services:
  - type: web
    name: perfect-pals # the name of this service, you should change this
    runtime: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2

  # worker is not available for free plan
  # - name: perfect_pals
  #   type: worker
  #   env: ruby
  #   plan: free
  #   buildCommand: bundle install
  #   startCommand: bundle exec good_job start
  #   envVars:
  #     - key: SECRET_KEY_BASE
  #       generateValue: true
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: perfect_pals
  #         property: connectionString
  #     - key: RAILS_MASTER_KEY
  #       sync: false
  #     - key: RAILS_ENV
  #       value: production
  #     - key: GOOD_JOB_MAX_THREADS
  #       value: 5

databases: # this section provides some additional database configuration
  - name: db
    plan: free
    ipAllowList: []
